spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    showSql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  datasource:
    url: jdbc:mariadb://guavamap.com:3306/moboo
    username: '{cipher}5ffccf12d20dad1565a368b4cd5274353620e87d5959d8eb970f4d997484fa2c'
    password: '{cipher}e023097c9793a6a65822cb39c63f274100a6c32004a08c97362f7608640b5009'
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 10000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
      idle-timeout: 10000
      max-lifetime: 420000

app:
  ui:
    url: http://drawpick.com
